### ISSUE TITLE
ModuleNotFoundError: No module named 'basic_rnn_cells'

### ISSUE THREAD

**Issue by susht3** [gitabcworld/skiprnn_pytorch#1]
when i run your code, i get this error:

Traceback (most recent call last):
  File "01_adding_task.py", line 19, in <module>
    from util.graph_definition import *
  File "/mnt/d/skiprnn_pytorch/util/graph_definition.py", line 14, in <module>
    from rnn_cells.custom_cells import CBasicLSTMCell, CBasicGRUCell, \
  File "/mnt/d/skiprnn_pytorch/rnn_cells/custom_cells.py", line 7, in <module>
    from basic_rnn_cells import BasicLSTMCell, BasicGRUCell
ModuleNotFoundError: No module named 'basic_rnn_cells'

**Comment by gitabcworld** [comment]
Have you executed the 01_adding_task.py code from the root folder skiprnn?

**Comment by BinWang28** [comment]
You should change this line.
#Delete
from basic_rnn_cells import BasicLSTMCell, BasicGRUCell
#Add
from rnn_cells.basic_rnn_cells import BasicLSTMCell, BasicGRUCell

Then it should work well.

**Comment by gitabcworld** [comment]
Thanks for the help. I have changed these paths at the code.
