### ISSUE TITLE
What version of pytorch?

### ISSUE THREAD

**Issue by BinWang28** [gitabcworld/skiprnn_pytorch#2]
Thanks for your excellent work! Can you provide us with the pytorch version. Because there are some changes being made and I cannot run your code using 0.3.X version. Since the class of RNN cell is changed.

**Comment by BinWang28** [comment]
I have checked. It should be 0.4. Right? But it seems the official website closed the installation of 0.4 verison. Sad....

**Comment by gitabcworld** [comment]
Hi! Thanks. This project was done with the 0.4 master branch pytorch version, as you say.

**Comment by BinWang28** [comment]
Are you installing 0.4 master version from source？ I have tried conda and pip. They all give me 0.3 version.

**Comment by gitabcworld** [comment]
Yes, I have pytorch installed from source. There should not be many differences between the master 0.4 and 0.3 to adapt this code.

**Comment by BinWang28** [comment]
Thanks! Dude! I can successfully run your code!
