### ISSUE TITLE
Running any experiment

### ISSUE THREAD

**Issue by Abhi-Tiw1** [gitabcworld/skiprnn_pytorch#3]
When I try to run any experiment from the downloaded code, I directly get the error:

AttributeError: 'CSkipLSTMCell' object has no attribute 'check_forward_input'

I looked into the custom_cells.py and other files (with the base class) can't see find where it is initialized in.

**Comment by gitabcworld** [comment]
I used the master version of Pytorch, to develop this code. The function 'check_forward_input' from the class RNNCellBase, at the file torch/nn/modules/rnn.py is included at the 0.4 version of Pytorch. You can comment the lines at the code where 'check_forward_input' appears, if you want to make it work. They are only asserts to check if the dimensions of the Tensors are correct.
