### ISSUE TITLE
No Convergence seen for addition task

### ISSUE THREAD

**Issue by Abhi-Tiw1** [gitabcworld/skiprnn_pytorch#4]
Hi!

I am running a replication study between the tensor flow and pytorch implementation and for the addition task, no convergence is seen i.e. the number of validation samples don't go down at all or do that really slowly (remain always around 99% to 97% running with cuda overnight), compared to this the tensor flow code shows skipping sample behavior just after the first 300 iterations.

I could not spot any immediate difference between the two implementations (I am more used to pytorch).

Thanks
Abhishek

**Comment by Abhi-Tiw1** [comment]
I further investigated it and it seems the convergence is highly dependent on the random seed chosen for torch. Is there any specific that we should be using in this case?

**Comment by Abhi-Tiw1** [comment]
Hi!

I finally managed to find the bug in this code and have a solution. Further, I have done the Imdb experiment as well and all the results are replicable. Is there any way I can add my changes to this repository?

Abhishek

**Comment by gitabcworld** [comment]
Hi! Thanks a lot for your effort in finding this bug. I have merged the changes already. 
Sorry for the late reply.
